<?xml version="1.0"?>
<robot name="diff_car" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 参数 -->
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_width"  value="0.025"/>
  <xacro:property name="base_length"  value="0.26"/>
  <xacro:property name="base_width"   value="0.11"/>
  <xacro:property name="base_height"  value="0.017"/>

  <!-- base_link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.1 0.3 0.9 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.000517" ixy="0.0"    ixz="0.0"
               iyy="0.00283"  iyz="0.0"
               izz="0.00332"/>
    </inertial>
  </link>

  <!-- 正确格式的 xacro:macro -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <origin rpy="1.5708 0 0"/> <!-- 轮子横放 -->
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>

      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <surface>
          <contact>
            <ode/>
          </contact>
          <friction>
            <ode>
              <!-- 摩擦系数 -->
              <mu>0.7</mu>
              <mu2>0.7</mu2>
            </ode>
          </friction>
        </surface>
      </collision>


      <inertial>
        <mass value="0.025"/>
        <inertia ixx="9.0e-06"  ixy="0.0"    ixz="0.0"
                 iyy="9.0e-06"  iyz="0.0"
                 izz="1.53e-05"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} -${base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/> <!-- 轮子绕Y轴转动 -->
    </joint>
  </xacro:macro>

  <!-- 四个轮子 -->
  <xacro:wheel name="left_front_wheel"
               x="${0.3 * base_length}"
               y="${ base_width / 2}" />

  <xacro:wheel name="right_front_wheel"
               x="${0.3 * base_length}"
               y="${-base_width / 2}" />

  <xacro:wheel name="left_behind_wheel"
               x="${-0.3 * base_length}"
               y="${ base_width / 2}" />

  <xacro:wheel name="right_behind_wheel"
               x="${-0.3 * base_length}"
               y="${-base_width / 2}" />
              
  <!-- ros2_control 硬件 + 关节接口声明 -->
  <ros2_control name="diff_car_system" type="system">
    <hardware>
      <!-- 使用 Gazebo 提供的虚拟硬件 -->
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <!-- 每个轮子关节都声明 velocity 接口 -->
    <joint name="left_front_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="right_front_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="left_behind_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="right_behind_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>
          
  <!-- Gazebo 里加载 ros2_control 插件 -->
  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <!-- 告诉 gazebo_ros2_control 用哪个硬件插件（和上面 <ros2_control> 对应） -->
      <robot_sim_type>gazebo_ros2_control/GazeboSystem</robot_sim_type>

      <!-- 告诉它 robot_description 在哪个参数里、在哪个节点 -->
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>

      <!-- 告诉它 ros2_control 的配置 YAML 放在哪 -->
      <robot_namespace>/diff_car</robot_namespace>
      <parameters>$(find botlab_diff_description)/config/diff_car_ros2_control.yaml</parameters>
    </plugin>
  </gazebo>


</robot>
