<?xml version="1.0"?>
<robot name="diff_car" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 参数 -->
  <xacro:property name="wheel_radius" value="0.03"/>
  <xacro:property name="wheel_width"  value="0.02"/>
  <xacro:property name="base_length"  value="0.20"/>
  <xacro:property name="base_width"   value="0.15"/>
  <xacro:property name="base_height"  value="0.05"/>

  <!-- base_link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.1 0.3 0.9 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.02"/>
    </inertial>
  </link>

  <!-- 正确格式的 xacro:macro -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <origin rpy="1.5708 0 0"/> <!-- 轮子横放 -->
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>

      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} -${base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/> <!-- 轮子绕Y轴转动 -->
    </joint>
  </xacro:macro>

  <!-- 四个轮子 -->
  <xacro:wheel name="left_front_wheel"
               x="${0.3 * base_length}"
               y="${ base_width / 2}" />

  <xacro:wheel name="right_front_wheel"
               x="${0.3 * base_length}"
               y="${-base_width / 2}" />

  <xacro:wheel name="left_behind_wheel"
               x="${-0.3 * base_length}"
               y="${ base_width / 2}" />

  <xacro:wheel name="right_behind_wheel"
               x="${-0.3 * base_length}"
               y="${-base_width / 2}" />

  <!-- Gazebo 差速驱动插件 -->
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
        <!-- 不做重映射，直接用 /cmd_vel -->
        <remapping>cmd_vel:=cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
      </ros>

      <!-- 先只用前轮两个 joint，名字必须和上面的 joint 一模一样 -->
      <left_joint>left_front_wheel_joint</left_joint>
      <right_joint>right_front_wheel_joint</right_joint>

      <wheel_separation>${base_width}</wheel_separation>
      <wheel_diameter>${2 * wheel_radius}</wheel_diameter>

      <update_rate>50</update_rate>
      <max_wheel_torque>5.0</max_wheel_torque>
      <max_wheel_acceleration>3.0</max_wheel_acceleration>
      <command_timeout>1.0</command_timeout>

      <publish_tf>true</publish_tf>
      <odometry_source>0</odometry_source>
    </plugin>
  </gazebo>

</robot>
